# Shared by the standalone USB probe and the Bluetooth-backed root target.
# Include before pico_sdk_init() so every mbedTLS source uses the same config.
set(SWITCH2_USB_PROBE_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(PICO_MBEDTLS_CONFIG_FILE "${SWITCH2_USB_PROBE_DIR}/mbedtls_config.h")

function(switch2_usb_probe_configure target)
    set(probe_sources
        ${SWITCH2_USB_PROBE_DIR}/main.c
        ${SWITCH2_USB_PROBE_DIR}/protocol.c
        ${SWITCH2_USB_PROBE_DIR}/storage.cpp
        ${SWITCH2_USB_PROBE_DIR}/button_test.c)
    target_compile_features(${target} PRIVATE c_std_11 cxx_std_17)
    target_include_directories(${target} PRIVATE
        ${SWITCH2_USB_PROBE_DIR}
        ${SWITCH2_USB_PROBE_DIR}/../../src/firmware
        ${CMAKE_CURRENT_BINARY_DIR}
        ${PICO_SDK_PATH}/src/rp2_common/pico_btstack/include
        ${PICO_SDK_PATH}/lib/btstack/platform/embedded)
    target_compile_definitions(${target} PRIVATE
        CFG_TUSB_CONFIG_FILE="${SWITCH2_USB_PROBE_DIR}/tusb_config.h")
    option(SWITCH2_PROBE_TRACE_NATIVE_INPUT
        "Trace one completed native USB input report per second without changing its contents" OFF)
    if(SWITCH2_PROBE_TRACE_NATIVE_INPUT)
        if(NOT SWITCH_PICO_SWITCH2_USB_BRIDGE)
            message(FATAL_ERROR "Native input tracing requires the Bluetooth USB bridge")
        endif()
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_TRACE_NATIVE_INPUT=1)
    endif()
    if(SWITCH2_BRIDGE_WII_INPUT)
        set(SWITCH2_WII_IR_SENSITIVITY 3 CACHE STRING "Standard Wii camera sensitivity preset: 2 or 3")
        set_property(CACHE SWITCH2_WII_IR_SENSITIVITY PROPERTY STRINGS 2 3)
        if(NOT "${SWITCH2_WII_IR_SENSITIVITY}" MATCHES "^[23]$")
            message(FATAL_ERROR "SWITCH2_WII_IR_SENSITIVITY must be standard preset 2 or 3")
        endif()
        target_compile_definitions(bluepad32 PRIVATE
            SWITCH_PICO_WII_IR_SENSITIVITY_LEVEL=${SWITCH2_WII_IR_SENSITIVITY})
        set(SWITCH2_WII_IR_VIEW_WIDTH 660 CACHE STRING "Native Wii IR viewport width in camera pixels")
        set(SWITCH2_WII_IR_VIEW_HEIGHT 370 CACHE STRING "Native Wii IR viewport height in camera pixels")
        set(SWITCH2_WII_IR_OFFSET_X 0 CACHE STRING "Native Wii IR viewport horizontal camera offset")
        set(SWITCH2_WII_IR_OFFSET_Y -115 CACHE STRING "Native Wii IR viewport vertical offset: -115 below, +115 above")
        set(SWITCH2_WII_IR_SPAN_X 1920 CACHE STRING "Native mouse counts across the IR viewport width")
        set(SWITCH2_WII_IR_SPAN_Y 1080 CACHE STRING "Native mouse counts across the IR viewport height")
        foreach(field VIEW_WIDTH VIEW_HEIGHT OFFSET_X OFFSET_Y SPAN_X SPAN_Y)
            if(NOT "${SWITCH2_WII_IR_${field}}" MATCHES "^-?[0-9]+$")
                message(FATAL_ERROR "SWITCH2_WII_IR_${field} must be an integer")
            endif()
        endforeach()
        math(EXPR offset_x_twice "2 * ${SWITCH2_WII_IR_OFFSET_X}")
        math(EXPR offset_y_twice "2 * ${SWITCH2_WII_IR_OFFSET_Y}")
        math(EXPR room_x "1024 - ${SWITCH2_WII_IR_VIEW_WIDTH}")
        math(EXPR room_y "768 - ${SWITCH2_WII_IR_VIEW_HEIGHT}")
        if(SWITCH2_WII_IR_VIEW_WIDTH LESS 1 OR SWITCH2_WII_IR_VIEW_WIDTH GREATER 1024 OR
           SWITCH2_WII_IR_VIEW_HEIGHT LESS 1 OR SWITCH2_WII_IR_VIEW_HEIGHT GREATER 768 OR
           offset_x_twice LESS -${room_x} OR offset_x_twice GREATER ${room_x} OR
           offset_y_twice LESS -${room_y} OR offset_y_twice GREATER ${room_y} OR
           SWITCH2_WII_IR_SPAN_X LESS 1 OR SWITCH2_WII_IR_SPAN_X GREATER 32767 OR
           SWITCH2_WII_IR_SPAN_Y LESS 1 OR SWITCH2_WII_IR_SPAN_Y GREATER 32767)
            message(FATAL_ERROR "Native IR viewport must lie inside the camera; mouse spans must be 1..32767")
        endif()
        target_compile_definitions(${target} PRIVATE
            SWITCH2_WII_IR_SCREEN_CONFIG=${SWITCH2_WII_IR_VIEW_WIDTH},${SWITCH2_WII_IR_VIEW_HEIGHT},${SWITCH2_WII_IR_OFFSET_X},${SWITCH2_WII_IR_OFFSET_Y},${SWITCH2_WII_IR_SPAN_X},${SWITCH2_WII_IR_SPAN_Y})
    endif()
    option(SWITCH2_PROBE_OMIT_NATIVE_IMU
        "Activation experiment: omit only native IMU bytes while retaining advertised features" OFF)
    option(SWITCH2_PROBE_ZERO_NATIVE_IMU_PAYLOAD
        "Activation experiment: zero native IMU payload while preserving its length" OFF)
    if(SWITCH2_PROBE_OMIT_NATIVE_IMU AND SWITCH2_PROBE_ZERO_NATIVE_IMU_PAYLOAD)
        message(FATAL_ERROR "Select only one IMU activation experiment")
    endif()
    if(SWITCH2_PROBE_OMIT_NATIVE_IMU OR SWITCH2_PROBE_ZERO_NATIVE_IMU_PAYLOAD)
        if(NOT SWITCH_PICO_SWITCH2_USB_BRIDGE)
            message(FATAL_ERROR "Native IMU activation experiments require the Bluetooth USB bridge")
        endif()
        if(SWITCH2_BRIDGE_WII_INPUT)
            message(FATAL_ERROR "Disable IMU ablation experiments for the Wii source bridge")
        endif()
    endif()
    if(SWITCH2_PROBE_OMIT_NATIVE_IMU)
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_OMIT_NATIVE_IMU=1)
    elseif(SWITCH2_PROBE_ZERO_NATIVE_IMU_PAYLOAD)
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_ZERO_NATIVE_IMU_PAYLOAD=1)
    endif()

    set(SWITCH2_PROBE_IDENTITY_FILE "" CACHE FILEPATH "64-byte Joy-Con 2 (R) factory-format identity block")
    if(SWITCH2_PROBE_IDENTITY_FILE)
        file(READ "${SWITCH2_PROBE_IDENTITY_FILE}" identity_hex LIMIT 65 HEX)
        string(LENGTH "${identity_hex}" identity_length)
        if(NOT identity_length EQUAL 128)
            message(FATAL_ERROR "Identity capture must contain exactly 64 bytes")
        endif()
        string(TOLOWER "${identity_hex}" identity_hex)
        string(SUBSTRING "${identity_hex}" 36 8 identity_vid_pid)
        if(NOT identity_vid_pid STREQUAL "7e056620")
            message(FATAL_ERROR "Identity capture must match Joy-Con 2 (R), 057e:2066")
        endif()
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," identity_bytes "${identity_hex}")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/probe_identity.h"
            "// Generated from a private, read-only controller capture; do not commit.\n#include <stdint.h>\nstatic const uint8_t probe_identity_reply[64] = {${identity_bytes}};\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${SWITCH2_PROBE_IDENTITY_FILE}")
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_IDENTITY_REPLY=1)
    endif()
    set(SWITCH2_PROBE_VERSION_FILE "" CACHE FILEPATH "Captured 12-byte Joy-Con 2 (R) firmware-version reply")
    set(SWITCH2_PROBE_CONTROLLER_ADDRESS "" CACHE STRING "Advertised controller address (captured or distinct virtual identity)")
    if(SWITCH2_PROBE_VERSION_FILE)
        if(NOT SWITCH2_PROBE_IDENTITY_FILE)
            message(FATAL_ERROR "Version response requires the matching identity capture")
        endif()
        file(READ "${SWITCH2_PROBE_VERSION_FILE}" version_hex LIMIT 13 HEX)
        string(LENGTH "${version_hex}" version_length)
        if(NOT version_length EQUAL 24)
            message(FATAL_ERROR "Firmware version capture must contain exactly 12 bytes")
        endif()
        string(TOLOWER "${version_hex}" version_hex)
        string(SUBSTRING "${version_hex}" 6 2 firmware_type)
        if(NOT firmware_type STREQUAL "01")
            message(FATAL_ERROR "Firmware version capture must describe Joy-Con 2 (R)")
        endif()
        string(REPLACE ":" "" address_hex "${SWITCH2_PROBE_CONTROLLER_ADDRESS}")
        string(TOLOWER "${address_hex}" address_hex)
        string(LENGTH "${address_hex}" address_length)
        if(NOT address_length EQUAL 12 OR NOT address_hex MATCHES "^[0-9a-f]+$")
            message(FATAL_ERROR "Provide a six-byte advertised controller Bluetooth address")
        endif()
        set(address_reversed "")
        foreach(byte RANGE 0 5)
            math(EXPR position "10 - 2 * ${byte}")
            string(SUBSTRING "${address_hex}" ${position} 2 octet)
            string(APPEND address_reversed "${octet}")
        endforeach()
        string(SUBSTRING "${version_hex}" 0 6 main_version)
        string(SUBSTRING "${version_hex}" 8 6 bluetooth_version)
        # Layout corroborated against two genuine USB vendor-02 responses and their
        # matching command-10 version and command-15 address responses.
        set(status_hex "${main_version}000000${bluetooth_version}00${address_reversed}")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," status_bytes "${status_hex}")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," firmware_bytes "${version_hex}")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/probe_version.h"
            "// Generated from private controller captures; do not commit.\n#include <stdint.h>\nstatic const uint8_t probe_version_reply[16] = {${status_bytes}};\nstatic const uint8_t probe_firmware_version[12] = {${firmware_bytes}};\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${SWITCH2_PROBE_VERSION_FILE}")
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_VERSION_REPLY=1)
    endif()
    option(SWITCH2_PROBE_ACK_SETUP04 "Acknowledge the observed vendor-04 setup transaction" OFF)
    if(SWITCH2_PROBE_ACK_SETUP04)
        if(NOT SWITCH2_PROBE_IDENTITY_FILE OR NOT SWITCH2_PROBE_VERSION_FILE)
            message(FATAL_ERROR "Setup acknowledgement requires both verified controller replies")
        endif()
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_ACK_SETUP04=1)
    endif()
    option(SWITCH2_PROBE_USB_INIT "Implement documented USB init and stream neutral diagnostic reports" OFF)
    if(SWITCH2_PROBE_USB_INIT)
        if(NOT SWITCH2_PROBE_ACK_SETUP04)
            message(FATAL_ERROR "USB initialization probe requires the verified setup acknowledgement")
        endif()
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_USB_INIT=1)
    endif()
    set(SWITCH2_PROBE_FACTORY_FILE "" CACHE FILEPATH "8192-byte captured factory region with configured virtual identity")
    set(SWITCH2_PROBE_USER_CALIBRATION_FILE "" CACHE FILEPATH "4096-byte captured user calibration region")
    if(SWITCH2_PROBE_FACTORY_FILE OR SWITCH2_PROBE_USER_CALIBRATION_FILE)
        if(NOT SWITCH2_PROBE_USB_INIT OR NOT SWITCH2_PROBE_FACTORY_FILE OR NOT SWITCH2_PROBE_USER_CALIBRATION_FILE)
            message(FATAL_ERROR "Memory replies require initialized USB and both calibration captures")
        endif()
        file(READ "${SWITCH2_PROBE_FACTORY_FILE}" factory_hex LIMIT 8193 HEX)
        file(READ "${SWITCH2_PROBE_USER_CALIBRATION_FILE}" user_calibration_hex LIMIT 4097 HEX)
        string(LENGTH "${factory_hex}" factory_length)
        string(LENGTH "${user_calibration_hex}" user_calibration_length)
        if(NOT factory_length EQUAL 16384 OR NOT user_calibration_length EQUAL 8192)
            message(FATAL_ERROR "Factory/user captures must contain exactly 8192/4096 bytes")
        endif()
        string(SUBSTRING "${factory_hex}" 0 128 factory_identity_hex)
        if(NOT factory_identity_hex STREQUAL identity_hex)
            message(FATAL_ERROR "Factory memory identity must match the vendor-control identity")
        endif()
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," factory_bytes "${factory_hex}")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," user_calibration_bytes "${user_calibration_hex}")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/probe_memory_data.h"
            "// Generated from private calibration captures; do not commit.\n#include <stdint.h>\nstatic const uint8_t probe_factory_memory[8192] = {${factory_bytes}};\nstatic const uint8_t probe_user_calibration[4096] = {${user_calibration_bytes}};\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            "${SWITCH2_PROBE_FACTORY_FILE}" "${SWITCH2_PROBE_USER_CALIBRATION_FILE}")
        list(APPEND probe_sources ${SWITCH2_USB_PROBE_DIR}/memory.c)
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_MEMORY=1)
    endif()
    target_sources(${target} PRIVATE ${probe_sources})
    set(probe_compile_options -Wall -Wextra -Werror)
    if(SWITCH_PICO_SWITCH2_USB_BRIDGE)
        # Preserve the root firmware's warning policy outside the probe sources.
        set_source_files_properties(${probe_sources} PROPERTIES
            COMPILE_OPTIONS "${probe_compile_options}")
    else()
        target_compile_options(${target} PRIVATE ${probe_compile_options})
    endif()
    target_link_libraries(${target} PRIVATE pico_stdlib hardware_uart hardware_sync
        hardware_flash pico_flash pico_mbedtls_crypto pico_mbedtls_headers tinyusb_device)
    pico_enable_stdio_usb(${target} 0)
    pico_enable_stdio_uart(${target} 1)
    if(SWITCH2_BRIDGE_WII_INPUT)
        pico_set_program_name(${target} "Switch 2 Wii IR and native motion bridge")
    elseif(SWITCH_PICO_SWITCH2_USB_BRIDGE)
        pico_set_program_name(${target} "Switch 2 right Joy-Con Bluetooth bridge")
    else()
        pico_set_program_name(${target} "Switch 2 USB initialization capture")
    endif()
    if(SWITCH2_PROBE_OMIT_NATIVE_IMU)
        pico_set_program_version(${target} "0.24-no-imu")
    elseif(SWITCH2_PROBE_ZERO_NATIVE_IMU_PAYLOAD)
        pico_set_program_version(${target} "0.24-zero-imu-payload")
    elseif(SWITCH2_BRIDGE_WII_INPUT)
        if(SWITCH2_PROBE_TRACE_NATIVE_INPUT)
            pico_set_program_version(${target} "0.33-wii-trace")
        else()
            pico_set_program_version(${target} "0.33-wii")
        endif()
    elseif(SWITCH_PICO_SWITCH2_USB_BRIDGE)
        if(SWITCH2_PROBE_TRACE_NATIVE_INPUT)
            pico_set_program_version(${target} "0.25-trace")
        else()
            pico_set_program_version(${target} "0.25")
        endif()
    else()
        pico_set_program_version(${target} "0.24")
    endif()
endfunction()
