# Shared by the standalone USB probe and the Bluetooth-backed root target.
# Include before pico_sdk_init() so every mbedTLS source uses the same config.
set(SWITCH2_USB_PROBE_DIR "${CMAKE_CURRENT_LIST_DIR}")
set(PICO_MBEDTLS_CONFIG_FILE "${SWITCH2_USB_PROBE_DIR}/mbedtls_config.h")

function(switch2_usb_probe_configure target)
    set(probe_sources
        ${SWITCH2_USB_PROBE_DIR}/main.c
        ${SWITCH2_USB_PROBE_DIR}/protocol.c
        ${SWITCH2_USB_PROBE_DIR}/storage.cpp
        ${SWITCH2_USB_PROBE_DIR}/button_test.c)
    target_compile_features(${target} PRIVATE c_std_11 cxx_std_17)
    target_include_directories(${target} PRIVATE
        ${SWITCH2_USB_PROBE_DIR}
        ${SWITCH2_USB_PROBE_DIR}/../../src/firmware
        ${CMAKE_CURRENT_BINARY_DIR}
        ${PICO_SDK_PATH}/src/rp2_common/pico_btstack/include
        ${PICO_SDK_PATH}/lib/btstack/platform/embedded)
    target_compile_definitions(${target} PRIVATE
        CFG_TUSB_CONFIG_FILE="${SWITCH2_USB_PROBE_DIR}/tusb_config.h")

    set(SWITCH2_PROBE_IDENTITY_FILE "" CACHE FILEPATH "64-byte Joy-Con 2 (R) factory-format identity block")
    if(SWITCH2_PROBE_IDENTITY_FILE)
        file(READ "${SWITCH2_PROBE_IDENTITY_FILE}" identity_hex LIMIT 65 HEX)
        string(LENGTH "${identity_hex}" identity_length)
        if(NOT identity_length EQUAL 128)
            message(FATAL_ERROR "Identity capture must contain exactly 64 bytes")
        endif()
        string(TOLOWER "${identity_hex}" identity_hex)
        string(SUBSTRING "${identity_hex}" 36 8 identity_vid_pid)
        if(NOT identity_vid_pid STREQUAL "7e056620")
            message(FATAL_ERROR "Identity capture must match Joy-Con 2 (R), 057e:2066")
        endif()
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," identity_bytes "${identity_hex}")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/probe_identity.h"
            "// Generated from a private, read-only controller capture; do not commit.\n#include <stdint.h>\nstatic const uint8_t probe_identity_reply[64] = {${identity_bytes}};\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${SWITCH2_PROBE_IDENTITY_FILE}")
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_IDENTITY_REPLY=1)
    endif()
    set(SWITCH2_PROBE_VERSION_FILE "" CACHE FILEPATH "Captured 12-byte Joy-Con 2 (R) firmware-version reply")
    set(SWITCH2_PROBE_CONTROLLER_ADDRESS "" CACHE STRING "Advertised controller address (captured or distinct virtual identity)")
    if(SWITCH2_PROBE_VERSION_FILE)
        if(NOT SWITCH2_PROBE_IDENTITY_FILE)
            message(FATAL_ERROR "Version response requires the matching identity capture")
        endif()
        file(READ "${SWITCH2_PROBE_VERSION_FILE}" version_hex LIMIT 13 HEX)
        string(LENGTH "${version_hex}" version_length)
        if(NOT version_length EQUAL 24)
            message(FATAL_ERROR "Firmware version capture must contain exactly 12 bytes")
        endif()
        string(TOLOWER "${version_hex}" version_hex)
        string(SUBSTRING "${version_hex}" 6 2 firmware_type)
        if(NOT firmware_type STREQUAL "01")
            message(FATAL_ERROR "Firmware version capture must describe Joy-Con 2 (R)")
        endif()
        string(REPLACE ":" "" address_hex "${SWITCH2_PROBE_CONTROLLER_ADDRESS}")
        string(TOLOWER "${address_hex}" address_hex)
        string(LENGTH "${address_hex}" address_length)
        if(NOT address_length EQUAL 12 OR NOT address_hex MATCHES "^[0-9a-f]+$")
            message(FATAL_ERROR "Provide a six-byte advertised controller Bluetooth address")
        endif()
        set(address_reversed "")
        foreach(byte RANGE 0 5)
            math(EXPR position "10 - 2 * ${byte}")
            string(SUBSTRING "${address_hex}" ${position} 2 octet)
            string(APPEND address_reversed "${octet}")
        endforeach()
        string(SUBSTRING "${version_hex}" 0 6 main_version)
        string(SUBSTRING "${version_hex}" 8 6 bluetooth_version)
        # Layout corroborated against two genuine USB vendor-02 responses and their
        # matching command-10 version and command-15 address responses.
        set(status_hex "${main_version}000000${bluetooth_version}00${address_reversed}")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," status_bytes "${status_hex}")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," firmware_bytes "${version_hex}")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/probe_version.h"
            "// Generated from private controller captures; do not commit.\n#include <stdint.h>\nstatic const uint8_t probe_version_reply[16] = {${status_bytes}};\nstatic const uint8_t probe_firmware_version[12] = {${firmware_bytes}};\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS "${SWITCH2_PROBE_VERSION_FILE}")
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_VERSION_REPLY=1)
    endif()
    option(SWITCH2_PROBE_ACK_SETUP04 "Acknowledge the observed vendor-04 setup transaction" OFF)
    if(SWITCH2_PROBE_ACK_SETUP04)
        if(NOT SWITCH2_PROBE_IDENTITY_FILE OR NOT SWITCH2_PROBE_VERSION_FILE)
            message(FATAL_ERROR "Setup acknowledgement requires both verified controller replies")
        endif()
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_ACK_SETUP04=1)
    endif()
    option(SWITCH2_PROBE_USB_INIT "Implement documented USB init and stream neutral diagnostic reports" OFF)
    if(SWITCH2_PROBE_USB_INIT)
        if(NOT SWITCH2_PROBE_ACK_SETUP04)
            message(FATAL_ERROR "USB initialization probe requires the verified setup acknowledgement")
        endif()
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_USB_INIT=1)
    endif()
    set(SWITCH2_PROBE_FACTORY_FILE "" CACHE FILEPATH "8192-byte captured factory region with configured virtual identity")
    set(SWITCH2_PROBE_USER_CALIBRATION_FILE "" CACHE FILEPATH "4096-byte captured user calibration region")
    if(SWITCH2_PROBE_FACTORY_FILE OR SWITCH2_PROBE_USER_CALIBRATION_FILE)
        if(NOT SWITCH2_PROBE_USB_INIT OR NOT SWITCH2_PROBE_FACTORY_FILE OR NOT SWITCH2_PROBE_USER_CALIBRATION_FILE)
            message(FATAL_ERROR "Memory replies require initialized USB and both calibration captures")
        endif()
        file(READ "${SWITCH2_PROBE_FACTORY_FILE}" factory_hex LIMIT 8193 HEX)
        file(READ "${SWITCH2_PROBE_USER_CALIBRATION_FILE}" user_calibration_hex LIMIT 4097 HEX)
        string(LENGTH "${factory_hex}" factory_length)
        string(LENGTH "${user_calibration_hex}" user_calibration_length)
        if(NOT factory_length EQUAL 16384 OR NOT user_calibration_length EQUAL 8192)
            message(FATAL_ERROR "Factory/user captures must contain exactly 8192/4096 bytes")
        endif()
        string(SUBSTRING "${factory_hex}" 0 128 factory_identity_hex)
        if(NOT factory_identity_hex STREQUAL identity_hex)
            message(FATAL_ERROR "Factory memory identity must match the vendor-control identity")
        endif()
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," factory_bytes "${factory_hex}")
        string(REGEX REPLACE "([0-9a-f][0-9a-f])" "0x\\1," user_calibration_bytes "${user_calibration_hex}")
        file(WRITE "${CMAKE_CURRENT_BINARY_DIR}/probe_memory_data.h"
            "// Generated from private calibration captures; do not commit.\n#include <stdint.h>\nstatic const uint8_t probe_factory_memory[8192] = {${factory_bytes}};\nstatic const uint8_t probe_user_calibration[4096] = {${user_calibration_bytes}};\n")
        set_property(DIRECTORY APPEND PROPERTY CMAKE_CONFIGURE_DEPENDS
            "${SWITCH2_PROBE_FACTORY_FILE}" "${SWITCH2_PROBE_USER_CALIBRATION_FILE}")
        list(APPEND probe_sources ${SWITCH2_USB_PROBE_DIR}/memory.c)
        target_compile_definitions(${target} PRIVATE SWITCH2_PROBE_MEMORY=1)
    endif()
    target_sources(${target} PRIVATE ${probe_sources})
    set(probe_compile_options -Wall -Wextra -Werror)
    if(SWITCH_PICO_SWITCH2_USB_BRIDGE)
        # Preserve the root firmware's warning policy outside the probe sources.
        set_source_files_properties(${probe_sources} PROPERTIES
            COMPILE_OPTIONS "${probe_compile_options}")
    else()
        target_compile_options(${target} PRIVATE ${probe_compile_options})
    endif()
    target_link_libraries(${target} PRIVATE pico_stdlib hardware_uart hardware_sync
        hardware_flash pico_flash pico_mbedtls_crypto pico_mbedtls_headers tinyusb_device)
    pico_enable_stdio_usb(${target} 0)
    pico_enable_stdio_uart(${target} 1)
    if(SWITCH_PICO_SWITCH2_USB_BRIDGE)
        pico_set_program_name(${target} "Switch 2 right Joy-Con Bluetooth bridge")
    else()
        pico_set_program_name(${target} "Switch 2 USB initialization capture")
    endif()
    pico_set_program_version(${target} "0.24")
endfunction()
