#ifndef SWITCH_PICO_CREDIT_BATCH_TEST_CONFIG_H
#define SWITCH_PICO_CREDIT_BATCH_TEST_CONFIG_H

#define ENABLE_CLASSIC
#define ENABLE_BLE
#define ENABLE_LE_CENTRAL
#define ENABLE_LE_PERIPHERAL
#define ENABLE_HCI_CONTROLLER_TO_HOST_FLOW_CONTROL
#define ENABLE_BTSTACK_ASSERT
#define HAVE_MALLOC
#define HCI_OUTGOING_PRE_BUFFER_SIZE 4
#define MAX_NR_HCI_CONNECTIONS 4
#define HCI_ACL_PAYLOAD_SIZE 1021
#define HCI_HOST_ACL_PACKET_LEN 1021
#define HCI_HOST_ACL_PACKET_NUM 3
#define HCI_HOST_SCO_PACKET_LEN 64
#define HCI_HOST_SCO_PACKET_NUM 3

#endif
